apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ljh-backend-shop-login-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jh-lee99/ljh-backend-shop-login.git
    targetRevision: HEAD
    path: overlays/dev/.
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
