apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ljh-was-login
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jh-lee99/ljh-was-login.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
